# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - redis:latest
  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  node_modules/

# 所有 stage 之前的操作
before_script:
  npm set registry https://github.com/395156224/sunny.git
  npm install


deploy_dev:
  script:
    # 构建
    vuepress build docs

    # 导航到构建输出目录
    cd docs/.vuepress/dist

    git init
    git add -A
    git commit -m 'deploy'

    # 推到你仓库的的 gh-page 分支
    git push -f git@github.com:395156224/395156224.github.io.git master:gh-pages
