# Default yarn install
# Default script	npm test
# Matrix keys	env, node_js
# Support	Travis CI

language: node_js
node_js:
  - "node"
  - "10"

env:
  - GITHUB_TOKEN=74e9655d7ec70ea7296d84527987a62e5548c087

cache:
  yarn: true
  directories:
    - /node_modules/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs/.vuepress/dist
  target-branch: https://github.com/395156224/395156224.github.io.git
  on:
    branch: master

before_install:

install:

before_script:

script:
  - yarn build