# Default yarn install
# Default script	npm test
# Matrix keys	env, node_js
# Support	Travis CI

language: node_js
node_js:
  - "node"
  - "10.8.0"

# env:
#   - GITHUB_TOKEN=6ed331fca4ccaab6dc408fd8f9aa1df26b0ff2e3

cache:
  yarn: true
  directories:
    - /node_modules/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs/.vuepress/dist
  target-branch: https://github.com/395156224/395156224.github.io.git
  on:
    branch: master

before_install:

install:

before_script:

script:
  - yarn build