# Default yarn install
# Default script	npm test
# Matrix keys	env, node_js
# Support	Travis CI

language: node_js
node_js:
  - "node"
  - "10.8.0"

env:
 global:
   - GH_REF: github.com/395156224/395156224.github.io.git

cache:
  yarn: true
  directories:
    - /node_modules/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs/.vuepress/dist
  # target-branch: github.com/395156224/395156224.github.io.git
  on:
    branch: master

before_install:

install:

before_script:

script:
  - yarn build

after_script:
  # 导航到构建输出目录
  - cd docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'Update Sunny Home Pages'

  # 推到你仓库的的 gh-page 分支
  # 将 <USERNAME>/<REPO> 替换为你的信息
  - git push --force --quiet  "https://${GITHUB_TOKEN}@${GH_REF}" master:master